(() => {
  const inventoryPage = document.getElementById('inventario');
  if (!inventoryPage) return;
  const client = (typeof sb !== 'undefined') ? sb : null;
  const css = `
  #inventario .inv-head{display:flex;justify-content:space-between;align-items:flex-end;gap:18px;margin-bottom:18px;flex-wrap:wrap}
  #inventario .inv-actions{display:flex;gap:9px;flex-wrap:wrap}
  #inventario .inv-btn{border:0;border-radius:10px;padding:11px 15px;font-weight:800;cursor:pointer}
  #inventario .inv-primary{background:var(--green);color:#fff}.inv-primary:hover{background:var(--green2)}
  #inventario .inv-secondary{background:#fff;border:1px solid var(--line);color:var(--ink)}
  #inventario .inv-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:16px}
  #inventario .inv-kpi{padding:17px}.inv-kpi-label{font-size:11px;color:var(--muted);font-weight:800;text-transform:uppercase}.inv-kpi-value{font-size:25px;font-weight:850;margin-top:8px}.inv-kpi-note{font-size:11px;color:var(--muted);margin-top:4px}
  #inventario .inv-toolbar{display:flex;gap:10px;align-items:center;padding:14px;border-bottom:1px solid var(--line);flex-wrap:wrap}
  #inventario .inv-search{flex:1;min-width:220px;padding:11px 13px;border:1px solid var(--line);border-radius:10px;background:#fbfcfc;outline:none}
  #inventario .inv-select{padding:11px 13px;border:1px solid var(--line);border-radius:10px;background:#fff}
  #inventario .inv-table-wrap{overflow:auto}.inv-table{min-width:900px}.inv-empty{text-align:center;padding:42px 20px;color:var(--muted)}
  #inventario .stock-ok{color:#087d54;background:#eaf8f1}.stock-low{color:#a56a0b;background:#fff3df}.stock-out{color:#a52f29;background:#ffe9e7}.inv-badge{display:inline-block;padding:5px 9px;border-radius:99px;font-size:11px;font-weight:800}
  #inventario .inv-modal{position:fixed;inset:0;background:#07100d80;display:none;align-items:center;justify-content:center;padding:20px;z-index:9999}.inv-modal.open{display:flex}.inv-dialog{width:min(620px,100%);background:#fff;border-radius:16px;box-shadow:0 20px 60px #0003;overflow:hidden}.inv-dialog-head{padding:18px 20px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.inv-dialog-head h3{margin:0}.inv-close{border:0;background:transparent;font-size:24px;cursor:pointer}.inv-form{padding:20px;display:grid;grid-template-columns:1fr 1fr;gap:14px}.inv-form .full{grid-column:1/-1}.inv-form label{display:block;font-size:12px;font-weight:800;margin-bottom:6px}.inv-form input,.inv-form select,.inv-form textarea{width:100%;padding:11px 12px;border:1px solid var(--line);border-radius:9px;background:#fbfcfc;outline:none;box-sizing:border-box}.inv-form textarea{min-height:75px;resize:vertical}.inv-form-foot{grid-column:1/-1;display:flex;justify-content:flex-end;gap:9px;margin-top:4px}
  @media(max-width:1000px){#inventario .inv-kpis{grid-template-columns:repeat(2,1fr)}}
  @media(max-width:620px){#inventario .inv-kpis{grid-template-columns:1fr}.inv-form{grid-template-columns:1fr}.inv-form .full{grid-column:auto}.inv-form-foot{grid-column:auto}}
  `;
  if (!document.getElementById('inventory-module-style')) { const s=document.createElement('style'); s.id='inventory-module-style'; s.textContent=css; document.head.appendChild(s); }
  inventoryPage.innerHTML = `
    <div class="inv-head"><div><div class="eyebrow">Gestión de existencias</div><h2 style="margin:8px 0 5px">Inventario</h2><p style="margin:0;color:var(--muted)">Materias primas, productos, envases e insumos de planta.</p></div><div class="inv-actions"><button type="button" class="inv-btn inv-secondary" id="invMovementBtn">＋ Movimiento</button><button type="button" class="inv-btn inv-primary" id="invNewBtn">＋ Nuevo artículo</button></div></div>
    <div class="inv-kpis"><div class="card inv-kpi"><div class="inv-kpi-label">Artículos</div><div class="inv-kpi-value" id="invCount">0</div><div class="inv-kpi-note">Catálogo activo</div></div><div class="card inv-kpi"><div class="inv-kpi-label">Valorización</div><div class="inv-kpi-value" id="invValue">S/ 0.00</div><div class="inv-kpi-note">Stock × costo unitario</div></div><div class="card inv-kpi"><div class="inv-kpi-label">Stock bajo</div><div class="inv-kpi-value" id="invLow">0</div><div class="inv-kpi-note">Requieren atención</div></div><div class="card inv-kpi"><div class="inv-kpi-label">Sin stock</div><div class="inv-kpi-value" id="invOut">0</div><div class="inv-kpi-note">Stock actual = 0</div></div></div>
    <div class="card"><div class="inv-toolbar"><input id="invSearch" class="inv-search" placeholder="Buscar por código, descripción o ubicación…"><select id="invCategory" class="inv-select"><option value="">Todas las categorías</option><option value="materia_prima">Materia prima</option><option value="producto_terminado">Producto terminado</option><option value="envase">Envase</option><option value="insumo">Insumo</option><option value="repuesto">Repuesto</option><option value="otro">Otro</option></select><select id="invStatus" class="inv-select"><option value="">Todos los estados</option><option value="ok">Normal</option><option value="low">Stock bajo</option><option value="out">Sin stock</option></select></div><div class="inv-table-wrap"><table class="table inv-table"><thead><tr><th>Código</th><th>Descripción</th><th>Categoría</th><th>Unidad</th><th>Ubicación</th><th>Stock</th><th>Mínimo</th><th>Costo unit.</th><th>Estado</th><th></th></tr></thead><tbody id="invRows"></tbody></table></div></div>
    <div id="invModal" class="inv-modal"><div class="inv-dialog"><div class="inv-dialog-head"><h3>Nuevo artículo</h3><button type="button" class="inv-close" id="invClose">×</button></div><form id="invForm" class="inv-form"><div><label>Código *</label><input id="invCode" required placeholder="MP-001"></div><div><label>Descripción *</label><input id="invName" required placeholder="Ácido sulfúrico 98%"></div><div><label>Categoría *</label><select id="invCat" required><option value="materia_prima">Materia prima</option><option value="producto_terminado">Producto terminado</option><option value="envase">Envase</option><option value="insumo">Insumo</option><option value="repuesto">Repuesto</option><option value="otro">Otro</option></select></div><div><label>Unidad *</label><input id="invUnit" required placeholder="kg, und, L…"></div><div><label>Stock inicial</label><input id="invStock" type="number" min="0" step="0.001" value="0"></div><div><label>Stock mínimo</label><input id="invMin" type="number" min="0" step="0.001" value="0"></div><div><label>Costo unitario (S/)</label><input id="invCost" type="number" min="0" step="0.0001" value="0"></div><div><label>Ubicación</label><input id="invLocation" placeholder="Almacén MP / Rack A1"></div><div class="full"><label>Observaciones</label><textarea id="invNotes"></textarea></div><div class="inv-form-foot"><button type="button" class="inv-btn inv-secondary" id="invCancel">Cancelar</button><button type="submit" class="inv-btn inv-primary">Guardar artículo</button></div></form></div></div>
    <div id="invMoveModal" class="inv-modal"><div class="inv-dialog"><div class="inv-dialog-head"><h3>Registrar movimiento</h3><button type="button" class="inv-close" id="invMoveClose">×</button></div><form id="invMoveForm" class="inv-form"><div class="full"><label>Artículo *</label><select id="moveItem" required></select></div><div><label>Tipo *</label><select id="moveType"><option value="entrada">Entrada</option><option value="salida">Salida</option><option value="ajuste">Ajuste</option></select></div><div><label>Cantidad *</label><input id="moveQty" type="number" min="0.001" step="0.001" required></div><div class="full"><label>Referencia / motivo</label><input id="moveRef" placeholder="Compra, producción, devolución, inventario físico…"></div><div class="inv-form-foot"><button type="button" class="inv-btn inv-secondary" id="moveCancel">Cancelar</button><button type="submit" class="inv-btn inv-primary">Registrar</button></div></form></div></div>`;
  const $=id=>document.getElementById(id); const money=n=>'S/ '+Number(n||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}); const catLabel={materia_prima:'Materia prima',producto_terminado:'Producto terminado',envase:'Envase',insumo:'Insumo',repuesto:'Repuesto',otro:'Otro'}; let items=[];
  const render=()=>{const q=($('invSearch').value||'').toLowerCase(),c=$('invCategory').value,st=$('invStatus').value;const filtered=items.filter(x=>{const stock=Number(x.stock_current||0),min=Number(x.min_stock||0),state=stock<=0?'out':stock<=min?'low':'ok';return(!q||[x.code,x.name,x.location].join(' ').toLowerCase().includes(q))&&(!c||x.category===c)&&(!st||state===st)});$('invRows').innerHTML=filtered.length?filtered.map(x=>{const stock=Number(x.stock_current||0),min=Number(x.min_stock||0),state=stock<=0?'out':stock<=min?'low':'ok';return `<tr><td><b>${x.code||''}</b></td><td>${x.name||''}</td><td>${catLabel[x.category]||x.category||''}</td><td>${x.unit||''}</td><td>${x.location||'—'}</td><td><b>${stock.toLocaleString('es-PE',{maximumFractionDigits:3})}</b></td><td>${min.toLocaleString('es-PE',{maximumFractionDigits:3})}</td><td>${money(x.unit_cost)}</td><td><span class="inv-badge ${state==='ok'?'stock-ok':state==='low'?'stock-low':'stock-out'}">${state==='ok'?'Normal':state==='low'?'Stock bajo':'Sin stock'}</span></td><td><button type="button" class="inv-btn inv-secondary" style="padding:7px 9px" data-move="${x.id}">Mover</button></td></tr>`}).join(''):`<tr><td colspan="10" class="inv-empty">No hay artículos que coincidan. Usa <b>Nuevo artículo</b> para comenzar.</td></tr>`;$('invCount').textContent=items.length;$('invValue').textContent=money(items.reduce((s,x)=>s+Number(x.stock_current||0)*Number(x.unit_cost||0),0));$('invLow').textContent=items.filter(x=>Number(x.stock_current||0)>0&&Number(x.stock_current||0)<=Number(x.min_stock||0)).length;$('invOut').textContent=items.filter(x=>Number(x.stock_current||0)<=0).length;$('invRows').querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>openMove(b.dataset.move));};
  async function load(){if(!client){render();return}const {data,error}=await client.from('inventory_items').select('*').eq('active',true).order('name');if(error){console.warn(error);render();return}items=data||[];render();}
  function openNew(){ $('invForm').reset(); $('invStock').value='0'; $('invMin').value='0'; $('invCost').value='0'; $('invModal').classList.add('open'); setTimeout(()=> $('invCode').focus(),50); }
  function closeNew(){ $('invModal').classList.remove('open'); }
  function openMove(id){ $('moveItem').innerHTML=items.map(x=>`<option value="${x.id}" ${String(x.id)===String(id)?'selected':''}>${x.code} · ${x.name} · stock ${x.stock_current}</option>`).join('');$('moveQty').value='';$('moveRef').value='';$('invMoveModal').classList.add('open');setTimeout(()=> $('moveQty').focus(),50); }
  const closeMove=()=> $('invMoveModal').classList.remove('open');
  $('invNewBtn').addEventListener('click',openNew);$('invClose').addEventListener('click',closeNew);$('invCancel').addEventListener('click',closeNew);$('invMovementBtn').addEventListener('click',()=>{if(items.length)openMove(items[0].id);else alert('Primero crea un artículo.')});$('invMoveClose').addEventListener('click',closeMove);$('moveCancel').addEventListener('click',closeMove);['invSearch','invCategory','invStatus'].forEach(id=>$(id).addEventListener('input',render));
  $('invForm').addEventListener('submit',async e=>{e.preventDefault();if(!client){alert('La conexión con Supabase no está disponible.');return}const payload={code:$('invCode').value.trim(),name:$('invName').value.trim(),category:$('invCat').value,unit:$('invUnit').value.trim(),stock_current:Number($('invStock').value||0),min_stock:Number($('invMin').value||0),unit_cost:Number($('invCost').value||0),location:$('invLocation').value.trim(),notes:$('invNotes').value.trim()};const {error}=await client.from('inventory_items').insert(payload);if(error){alert(error.message);return}closeNew();await load()});
  $('invMoveForm').addEventListener('submit',async e=>{e.preventDefault();if(!client){alert('La conexión con Supabase no está disponible.');return}const item=items.find(x=>String(x.id)===String($('moveItem').value)),qty=Number($('moveQty').value);if(!item||!qty)return;let delta=qty;if($('moveType').value==='salida')delta=-qty;const {error}=await client.from('inventory_movements').insert({item_id:item.id,movement_type:$('moveType').value,quantity:qty,quantity_change:delta,reference:$('moveRef').value.trim()});if(error){alert(error.message);return}closeMove();await load()});
  load();
})();