import { createProductionRun, createStageEvent, getStages } from './repository';

const stageOrder = ['TRANSFERENCIA', 'CARGA_VERIFICACION', 'MEZCLA_1', 'MEZCLA_2', 'MESA'];

export function renderProductionForm(root: HTMLElement, onSaved: () => void) {
  root.innerHTML = `<div class="qf-page-head"><div><span class="qf-eyebrow">OPERACIÓN</span><h2>Registro de producción</h2><p>Captura solo los datos necesarios para construir el historial operativo.</p></div></div>
  <form id="qfProductionForm" class="qf-form">
    <div class="qf-section"><h3>1. Lote</h3><div class="qf-grid"><label>Fecha<input name="run_date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Código de lote<input name="batch_code" required placeholder="Ej. L-2026-001"></label><label>Producto ID<input name="product_id" placeholder="Opcional"></label><label>Turno<select name="shift"><option>Mañana</option><option>Tarde</option><option>Noche</option></select></label><label>Plan (kg)<input name="planned_kg" type="number" min="0" step="0.01"></label><label>Producido (kg)<input name="produced_kg" type="number" min="0" step="0.01"></label><label>Rechazo (kg)<input name="rejected_kg" type="number" min="0" step="0.01" value="0"></label><label>Merma (kg)<input name="waste_kg" type="number" min="0" step="0.01" value="0"></label><label>Operadores totales<input name="operators_total" type="number" min="0" step="1"></label></div></div>
    <div class="qf-section"><h3>2. Etapas</h3><p class="qf-help">Registra inicio/fin y personas por etapa. Los tiempos de espera y parada alimentan el análisis de cuello de botella.</p><div id="qfStages"></div></div>
    <label>Observaciones<textarea name="notes" placeholder="Incidencias, esperas o causas relevantes..."></textarea></label>
    <div id="qfFormError" class="qf-error"></div><button class="qf-primary" type="submit">GUARDAR LOTE Y CALCULAR KPI</button>
  </form>`;
  const stages = root.querySelector('#qfStages')!;
  stages.innerHTML = stageOrder.map((name,i)=>`<div class="qf-stage"><strong>${i+1}. ${name.replaceAll('_',' ')}</strong><div class="qf-grid"><label>Inicio<input data-stage="${name}" data-field="start" type="datetime-local"></label><label>Fin<input data-stage="${name}" data-field="end" type="datetime-local"></label><label>Personas<input data-stage="${name}" data-field="operators" type="number" min="0" step="1"></label><label>Parada (min)<input data-stage="${name}" data-field="downtime" type="number" min="0" value="0"></label><label>Espera (min)<input data-stage="${name}" data-field="waiting" type="number" min="0" value="0"></label></div></div>`).join('');
  root.querySelector('#qfProductionForm')!.addEventListener('submit', async e => { e.preventDefault(); const form=e.currentTarget as HTMLFormElement; const data=new FormData(form); const err=root.querySelector('#qfFormError')!; err.textContent='Guardando...'; try { const run=await createProductionRun({run_date:String(data.get('run_date')),product_id:String(data.get('product_id')||'')||null,batch_code:String(data.get('batch_code')||'')||null,planned_kg:Number(data.get('planned_kg'))||null,produced_kg:Number(data.get('produced_kg'))||null,rejected_kg:Number(data.get('rejected_kg'))||0,waste_kg:Number(data.get('waste_kg'))||0,operators_total:Number(data.get('operators_total'))||null,shift:String(data.get('shift')),status:'completed',notes:String(data.get('notes')||'')||null}); for(const name of stageOrder){const get=(f:string)=>root.querySelector(`[data-stage="${name}"][data-field="${f}"]`) as HTMLInputElement; const start=get('start').value;if(!start)continue; await createStageEvent({production_run_id:run.id,stage_id:name,started_at:new Date(start).toISOString(),ended_at:get('end').value?new Date(get('end').value).toISOString():null,operators_count:Number(get('operators').value)||null,input_kg:null,output_kg:null,downtime_minutes:Number(get('downtime').value)||0,waiting_minutes:Number(get('waiting').value)||0,notes:null});} err.textContent='Lote guardado correctamente.'; onSaved(); } catch(ex){err.textContent=ex instanceof Error?ex.message:'No se pudo guardar el lote.';} });
}
